### ISSUE TITLE
Question regarding adding/removing servers

### ISSUE THREAD

**Issue by skyy-codes** [LunarClient/ServerMappings#1041]
Heya,

I had a question.

If I add my server here (already made PR) and want to remove it, should I just make a new PR to remove the server?

(not saying I want to remove it <3)

Thanks,

skyy

**Comment by ThatKawaiiSam** [comment]
Hey,

We never remove servers for archival purposes. Instead, we add them to our `inactive.json` so that they stop appearing across Lunar Client services.
