### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TrentaSei** [LunarClient/ServerMappings#1058]
i setted up both api plugin on my server and server mapping too but when me or one of my friend joins nothing changes. Logo, emotes and all the other things doesn't show up (the online mode is setted up as true) and i don't wanna change that, help?

**Comment by ethan-davies** [comment]
Could you provide me with more details about your situation? I'm struggling to understand your issue with the information you have provided.

**Comment by Frestylez** [comment]
Hello, something similar happens to me, I recently added my server in (server mappings), the only thing is that the logo that I put in the description is not visible (when you are in discord the server logo should appear as a description on the server you are connected to)

**Comment by astridlol** [comment]
> Hello, something similar happens to me, I recently added my server in (server mappings), the only thing is that the logo that I put in the description is not visible (when you are in discord the server logo should appear as a description on the server you are connected to)

Hey, at the time this issue was created, showing the servers logo within Discord was reserved for large servers due to how Lunars internals worked. As of November 20th, this feature was added for all servers registered in the mappings!

![image](https://github.com/LunarClient/ServerMappings/assets/45674371/c701af2e-a1a3-4f39-b41c-626bf1c3e58e)

**Comment by ThatKawaiiSam** [comment]
> > Hello, something similar happens to me, I recently added my server in (server mappings), the only thing is that the logo that I put in the description is not visible (when you are in discord the server logo should appear as a description on the server you are connected to)
> 
> Hey, at the time this issue was created, showing the servers logo within Discord was reserved for large servers due to how Lunars internals worked. As of November 20th, this feature was added for all servers registered in the mappings!
> 
> ![image](https://user-images.githubusercontent.com/45674371/284928266-c701af2e-a1a3-4f39-b41c-626bf1c3e58e.png)

As per @astridlol's message, Discord logos are now available to everyone! Ensure that your server is fully registered and is not deemed inactive an you should start seeing it.
