### ISSUE TITLE
Server Mapping / Logo

### ISSUE THREAD

**Issue by Frestylez** [LunarClient/ServerMappings#1092]
I recently added my server to server mappings, and apparently the logo in discord's rich precense does not appear, but rather a generic one appears, what should I change so that my server's appears?
![image](https://github.com/LunarClient/ServerMappings/assets/103514931/de44f44c-ff74-4d29-8852-b2cc0aa1bffa)

**Comment by ThatKawaiiSam** [comment]
Hi @Frestylez,

Only select servers (popular and partnered) logos appear in the Discord Rich Presence feature. This is due to a limitation within Discord itself with the amount of image asset slots available to our application.

I apologize for the inconvenience.
