### ISSUE TITLE
Server Mappings help

### ISSUE THREAD

**Issue by kytenpro** [LunarClient/ServerMappings#1229]
Hello, I wanted to configure the server mappings for my Minecraft server but when I verify I get a Cloudflare error and I wouldn't know how to fix this is the error. If you can help me, thank you very much and have a nice night. 

Run aws s3 sync .out s3://servermappings-lunarclientcdn-com --content-type "image/webp" --endpoint-url $R[2](https://github.com/kytenpro/ServerMappings/actions/runs/7094212018/job/19312376420#step:8:2)_ENDPOINT
  aws s3 sync .out s3://servermappings-lunarclientcdn-com --content-type "image/webp" --endpoint-url $R2_ENDPOINT
  aws s[3](https://github.com/kytenpro/ServerMappings/actions/runs/7094212018/job/19312376420#step:8:3) cp .out/servers.json s3://servermappings-lunarclientcdn-com/servers.json --content-type "application/json" --endpoint-url $R2_ENDPOINT
  aws s3 cp .out/servers.csv s3://servermappings-lunarclientcdn-com/servers.csv --content-type "text/csv" --endpoint-url $R2_ENDPOINT
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.0/x6[4](https://github.com/kytenpro/ServerMappings/actions/runs/7094212018/job/19312376420#step:8:4)
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.0/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.0/x64/lib
    R2_ENDPOINT: 
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    AWS_DEFAULT_REGION: us-east-1

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --endpoint-url: expected one argument

Error: Process completed with exit code 2[5](https://github.com/kytenpro/ServerMappings/actions/runs/7094212018/job/19312376420#step:8:5)2.

**Comment by wi** [comment]
er, what are you trying to do?
