### ISSUE TITLE
why you closed my pull request?

### ISSUE THREAD

**Issue by games4681** [LunarClient/ServerMappings#1357]
i open this pull request yesterday: https://github.com/LunarClient/ServerMappings/pull/1347
i have added star-gamess before a two months
i changed my server name and want to add my new details and add the new server and remove the old server. why you ignore to take a look? if there a problem with some details please let me know instend of just closed

**Comment by wi** [comment]
The bot responded to your PR on what needed to be fixed you didn't have it for two days after your PR was reviewed. You're able to make another pull request and as long as the bot adds the manual review tag and no manual requests are made for your PR it will be merged.
