### ISSUE TITLE
New logo of Wildya is not showing in the client

### ISSUE THREAD

**Issue by theFoxley** [LunarClient/ServerMappings#1370]
I updated the logo two weeks ago but it's not showing, did i do something wrong ? Or do i need to wait a little longer ?

![image](https://github.com/LunarClient/ServerMappings/assets/7950977/c3cd4089-13e1-4d4a-b3b0-8b96cb046699)

**Comment by Anakinnnnn** [comment]
They are separate to the server mappings one

**Comment by games4681** [comment]
> They are separate to the server mappings one

It's like that for me too, should I ask for deletion and re-adding in a pull request? Or wait until it is updated with the update you have already made?
