### ISSUE TITLE
My server has been incorrectly marked as inactive

### ISSUE THREAD

**Issue by RareMen666** [LunarClient/ServerMappings#1569]
My server is in China and has a DDOS defense. This DDOS defense only allows Chinese players to join the server and ping the server, so will this affect Lunar Client thinking that the server is down?

**Comment by ThatKawaiiSam** [comment]
Hey @RareMen666, is your server still in the inactive list? Could you please provide the ID so we can check it out.

**Comment by RareMen666** [comment]
> Hey @RareMen666, is your server still in the inactive list? Could you please provide the ID so we can check it out.

nope. very thanks！
