### ISSUE TITLE
Pull request creation failed. Validation failed: must be a collaborator

### ISSUE THREAD

**Issue by KareemKiwi** [LunarClient/ServerMappings#1727]
Each time i try to add my server i get this error `Pull request creation failed. Validation failed: must be a collaborator`

**Comment by wi** [comment]
You need to make a fork then create the [pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
