### ISSUE TITLE
Added Shivana

### ISSUE THREAD

**Issue by Syrql** [LunarClient/ServerMappings#1759]
[metadata.json](https://github.com/LunarClient/ServerMappings/files/14475031/metadata.json)
![logo png](https://github.com/LunarClient/ServerMappings/assets/41534598/106d49e1-cc26-4775-991b-0b91a8709f07)
![background](https://github.com/LunarClient/ServerMappings/assets/41534598/e373cd5f-18de-4c8d-8984-685fd74d9f1d)

**Comment by ThatKawaiiSam** [comment]
Hi, this is not the appropriate place to submit a server - you must open a Pull Request.
