### ISSUE TITLE
2 Separate servers in 1 entry

### ISSUE THREAD

**Issue by mishtavishta** [LunarClient/ServerMappings#1780]
The entry for the server "lifestealsmp" contains an IP which is actually owned by our network (play.lifesteal.rip), which doesn't currently have an entry.

https://github.com/LunarClient/ServerMappings/blob/master/servers/lifestealsmp/metadata.json

It would be nice if we were able to have our own entry as we are separate networks, thanks.

**Comment by wi** [comment]
In your PR remove the IP from their addresses array and just have it on yours
