### ISSUE TITLE
Add Mcvision

### ISSUE THREAD

**Issue by Cotam102** [LunarClient/ServerMappings#1857]
![2024-03-31_18-37-04](https://github.com/LunarClient/ServerMappings/assets/161765790/138e72e0-578d-4130-b456-4b3906cfe863)
![IMG_0688-kopia](https://github.com/LunarClient/ServerMappings/assets/161765790/0c2abc38-c7cd-4759-bb39-91abaf2cf130)

{
    "id": "mcvision",
    "name": "mcvision",
    "website": "https://mcvision.pl/",
    "store": "https://mcvision.pl/servers",
    "addresses": [
        "mcvision.pl"
    ],
    "primaryAddress": "mcvision.pl",
    "primaryColor": "#4f3eb8",
    "secondaryColor": "#150b54",
    "minecraftVersions": [
        "1.16.*",
        "1.17.*",
        "1.18.*",
        "1.19.*",
        "1.20.*"
    ],
    "primaryMinecraftVersion": "1.19.3",
    "primaryRegion": "EU",
    "regions": [
        "EU"
    ],
    "gameTypes": [
        "PvP"
    ],
    "socials": {
        "youtube":"mcvisionpl"
        "discord": "https://discord.com/invite/9rfrB9YGVS",
        "tiktok": "cotam102"
    }
}

**Comment by wi** [comment]
Hi, you need to follow the instructions [here](https://lunarclient.dev/server-mappings/adding-servers/overview) to get your server added.
