### ISSUE TITLE
Añadir Clunith Network

### ISSUE THREAD

**Issue by Regresad** [LunarClient/ServerMappings#1858]
![324245](https://github.com/LunarClient/ServerMappings/assets/165586655/018b9977-5002-47d2-a8c8-06b0037f91df)
  ip: clunith.Live
  modalida:
  Kitmap
  Gens Proximamente
  Discord; https://discord.gg/YFjRfJpWYg o Discord.Clunith.Live
  version 1.7 a 1.20
  espero que nos Acepten nuestra solicitud la imagen es 64x 64

**Comment by wi** [comment]
Hi you need to follow the instructions [here](https://lunarclient.dev/server-mappings/adding-servers/overview) to get your server added.
