### ISSUE TITLE
Server Adding

### ISSUE THREAD

**Issue by Mattix5673yt** [LunarClient/ServerMappings#1923]
How i do to add my server to lunarclient server add?

**Comment by vopswtf** [comment]
![image](https://github.com/LunarClient/ServerMappings/assets/55073114/e30cbd6d-4fef-4483-bcf8-8973c4521ee5)

**Comment by ThatKawaiiSam** [comment]
Hey @Mattix5673yt,

We have some documentation that may be able to assist you on our Developer website: https://lunarclient.dev/server-mappings/adding-servers/overview

Additionally, if you're still unsure and need some additional assistance, feel free to ask questions in the `#server-mappings` chat within our Developer discord: https://discord.gg/3T9Atyb6pf

**Comment by Mattix5673yt** [comment]
how i do to crate the pull request?
