### ISSUE TITLE
Warfine Network

### ISSUE THREAD

**Issue by Inxiify** [LunarClient/ServerMappings#2006]

**Comment by Inxiify** [comment]
![Warfine](https://github.com/LunarClient/ServerMappings/assets/155790418/3ffc547d-68fe-465d-89bf-1e9e6bf3a05b)

**Comment by Inxiify** [comment]
Warfine en la casa

**Comment by Inxiify** [comment]
[metadata.json.txt](https://github.com/LunarClient/ServerMappings/files/15213884/metadata.json.txt)

**Comment by wi** [comment]
Hi, you need to follow the instructions [here](https://lunarclient.dev/server-mappings/adding-servers/overview) to get your server added.
