### ISSUE TITLE
JediSky

### ISSUE THREAD

**Issue by KynnSs** [LunarClient/ServerMappings#2036]
[metadata.json](https://github.com/LunarClient/ServerMappings/files/15289643/metadata.json)
![logo](https://github.com/LunarClient/ServerMappings/assets/139001346/747e7dac-74d4-4333-a27c-a91b649cb122)

**Comment by WhyAydan** [comment]
Hi, Looks like you have meant to make a PR. Please follow the instructions [here](https://lunarclient.dev/server-mappings/adding-servers/overview) to get your server added.

**Comment by wi** [comment]
Hi, you need to follow the instructions [here](https://lunarclient.dev/server-mappings/adding-servers/overview) to get your server added.
