### ISSUE TITLE
Minecraft server status

### ISSUE THREAD

**Issue by SamueleX360** [LunarClient/ServerMappings#2048]
Samuele Gallio, reported a day ago
Hello gentlemen of the staff,
I have a question to ask you.
I've seen that when someone connects to a server with lunarclient it comes out "He's playing [servername] with the server icon. How would it be possible to have it since I also have a minecraft server?
A thousand thanks.
Best regards,
MrPingu

**Comment by wi** [comment]
Hi, yes in order for it to show the discord status you're server has to be added to the repository. Follow the instructions [here](https://lunarclient.dev/server-mappings/adding-servers/overview) to get your server added.
