### ISSUE TITLE
FalkoGames

### ISSUE THREAD

**Issue by FalkoYT** [LunarClient/ServerMappings#2220]
FalkoGames and a minecraft server 1.7 to 1.20 which offers players the possibility of playing their uhc game on it  ip: game1.falkoyt.fr
![Nkip0l1d_400x400](https://github.com/LunarClient/ServerMappings/assets/46298326/d8c30822-476a-4324-8547-1dc4bb58d984)

**Comment by Strokkur424** [comment]
Yeah uh, make a pull request
