### ISSUE TITLE
ServerMapping LOGO update Issue

### ISSUE THREAD

**Issue by Pol4rBe4r** [LunarClient/ServerMappings#2835]
Hi a few days ago, I updated the LOKAPSOS server logo, but in the Rich Presence of Discord, the old logo is displayed. In the servers/lokapos folder the logo that appears is the logo that should be displayed.

**New logo:**

![Captura](https://github.com/user-attachments/assets/62ed845f-9e52-4426-8380-ec15600817a4)

**Old logo:**

![image](https://github.com/user-attachments/assets/8c165cfb-deec-4442-a7a8-3813ec637764)

Best regards.

**Comment by NoaXelo** [comment]
Hello,
I have exactly the same problem, I updated the logo, it has been deployed, and this is my old logo that appears in the discord profile. 
Thank you for your help !

**Comment by trisout78** [comment]
#2807

**Comment by SnowzNZ** [comment]
+1

**Comment by wi** [comment]
Discord caches all images it will update whenever their cache expires and they refetch the image you can see that its updated [here](https://servermappings.lunarclientcdn.com/logos/lokapsos.png).
