### ISSUE TITLE
Error Rich Presence Discord

### ISSUE THREAD

**Issue by RuzitoTV** [LunarClient/ServerMappings#2983]
Hello, I'm here to report an error with the Discord presence.

A few hours ago I uploaded my server to the LunarClient ServersMappings Repository with its data, these were accepted but when I enter my server, it shows the information of another server that is not mine, I will attach an image and I hope the error can be corrected.

Link: https://github.com/LunarClient/ServerMappings/tree/master/servers/vyrexmcnet
![image](https://github.com/user-attachments/assets/c2cee813-722d-4163-b544-7ef6e4cc7222)

**Comment by Anakinnnnn** [comment]
Discord takes a long time to update it

**Comment by RuzitoTV** [comment]
Hi @Anakinnnnn 
I've been waiting a few days for what you told me through this conversation but the same thing still appears from another server. Could you help me please?

![image](https://github.com/user-attachments/assets/3b2afd5e-0d2f-4d08-aed1-c1c777387154)
