### ISSUE TITLE
Add FusionMC

### ISSUE THREAD

**Issue by FrancyPro** [LunarClient/ServerMappings#391]
{
        "id": "fusionmc",
        "name": "FusionMC",
        "addresses": [
            "play.fusionmc.ml",
            "mc.fusionmc.ml"
        ]
    },

**Comment by FrancyPro** [comment]
Icon: https://imgur.com/3OBRGCo

**Comment by GrowlyX** [comment]
Please create a pull request, not an issue.

**Comment by FrancyPro** [comment]
How create pull request
