### ISSUE TITLE
help

### ISSUE THREAD

**Issue by serumanooo** [LunarClient/ServerMappings#846]
someone explain to me what i have to do to add my server, i have the metadata.json, i have the background.png and i also have the logo.png files

but i cant understand how am i supposed to create the pull request, idk where do i add the files, i tried to add a these 3 files to the ServerMappings/servers/ by creating a file with the name of my server but i dont know where i am supposed to put these files

**Comment by Jxahn** [comment]
git add (changed files directory)
git commit -m (Messesge)
git push origin master

**Comment by serumanooo** [comment]
> git add (changed files directory) git commit -m (Messesge) git push origin master

what.

**Comment by Jxahn** [comment]
> > git add (changed files directory) git commit -m (Messesge) git push origin master
> 
> 
> 
> what.

?

**Comment by wi** [comment]
You need to make the pull request yourself we don't help with creating we only validate. You can use GitHub Desktop to create the pull request with a GUI but for further help use youtube.
