### ISSUE TITLE
API Problems

### ISSUE THREAD

**Issue by xiaohuihui1022** [LunarClient/ServerMappings#857]
I have problems with lunarclient API, I cannot even launch lunarclient
but if I use my browser to open API links, I can see all the thing that the API want the program to know.

And one thing that is really magical, if I try to launch lunarclient, I can launch it after several tries, but that is just the situation happens to  main form, if I try to launch the game, no matter how many times I tried, there are always errors(about API) or just stuck in UPDATEING the game with 100% progress.

I tried reinstalling, disabling my Firewall and Antivirus and changing my DNS server to 1.1.1.1 and 1.0.0.1. But they can't help me solve the problem, how can I solve it?

Here are the log files
[main.log](https://github.com/LunarClient/ServerMappings/files/12023166/main.log)
[renderer.log](https://github.com/LunarClient/ServerMappings/files/12023167/renderer.log)

**Comment by wi** [comment]
this isn't the place for this go to https://support.lunarclient.com/ for help with the client.
