### ISSUE TITLE
Missing Logos

### ISSUE THREAD

**Issue by ThatKawaiiSam** [LunarClient/ServerMappings#98]
The latest PR (#96) implements server logos as a _future_ requirement for server submissions. We are looking to locate the remaining server icons that we could not find ourselves. Please consult the README for the specifications for server logos (resolution, aspect ratio, etc).

The list goes as follows:
- [x] PvP Arcade
- [ ] Ukiyo
- [ ] Ukiyo Network
- [x] Kira
- [x] NeptuniumMC
- [ ] Domei
- [x] CraftPlay
- [x] TecnoCraft.net
- [x] Bridger Land
- [x] PvP Land
- [x] Silex Network
- [x] Valent Network
- [x] Syuu
- [ ] Chocolia
- [x] FlameMC
- [x] Glance Network
- [x] KoksCraft.pl
- [x] Bedwars Practice
- [x] Herobrine.org
- [x] Kwadratowa Games
- [x] CubeCraft Games
- [x] Greev.eu
- [x] SkyCraft Network
- [x] AntiAC
- [x] Ghostly Network
- [x] HYLEX.net
- [x] ZoneCraft Network
- [ ] Gamster.org
- [x] DragonSurvival.EU
- [x] UHC Arcade
- [ ] OnlyMC Network
- [x] Overcast Community
- [x] WaterMC
- [x] MCPrison
- [ ] SkyblockIsles.com
- [x] BlocksMC
- [x] PikaNetwork
- [ ] TabMC.pl
- [x] Inertia Network
- [ ] Vexor Network
- [ ] LynxMC Network
- [ ] Tempest Network
- [ ] Crowl Network
- [ ] InTroubleDE
- [ ] Ventry Combo
- [ ] ElectronMC
- [ ] Frozed Club
- [ ] MineLord Network
- [ ] Lust
- [ ] Kotlin
- [ ] Vanir Network
- [ ] Fyre Games
- [ ] MineKings
- [ ] LegionsMC Network
- [ ] Muffinized Network
- [ ] AriPvP Network
- [ ] Tyrex Network
- [ ] Vaporized Network
- [x] TeamFight Network
- [ ] CobelPvP Network
- [x] StarCraft MC
- [ ] VaultPvP Network
- [ ] TwistedMC
- [ ] Kosum Network
- [ ] Alpha Network
- [ ] Floppa Kingdom
- [ ] LordRealm Network
- [x] AlphaHQ Network
- [ ] BibliaMinecraft
- [ ] VF Network
- [ ] Scala
- [ ] Minequest

**Comment by ignBiometrical** [comment]
@ThatKawaiiSam Here is the logo for Inertia Network.
https://cdn.discordapp.com/icons/691086131994820658/a80975f25f767558d2bf731dacef9e2e.png?size=4096

**Comment by imconnorngl** [comment]
We are still looking for the following server logos:
-  Vexor Network
-  LynxMC Network
-  Tempest Network
-  Crowl Network
-  InTroubleDE
-  Ventry Combo
-  ElectronMC
-  Frozed Club
-  MineLord Network
-  Lust
-  Kotlin
- Vanir Network
-  Fyre Games
-  MineKings
-  LegionsMC Network
-  Muffinized Network
-  AriPvP Network
-  Tyrex Network
-  Vaporized Network
-  CobelPvP Network
-  VaultPvP Network
-  Kosum Network
-  Alpha Network
-  Floppa Kingdom
-  LordRealm Network
-  BibliaMinecraft
-  VF Network
- Scala
-  Chocolia
-  Minequest
-  TabMC.pl
-  OnlyMC Network
-  Domei
-  TwistedMC
-  Ukiyo
-  Ukiyo Network
-  Gamster.org
-  SkyblockIsles.com

**If these logos are not added to server mappings your server may be removed**
