### ISSUE TITLE
Developer Discord Invite Invalid

### ISSUE THREAD

**Issue by uniformization** [LunarClient/ServerMappings#995]
The Discord invite in [`docs/inactive-servers.mdx`](https://github.com/LunarClient/ServerMappings/blob/master/docs/inactive-servers.mdx#L5) is invalid.

**Comment by ThatKawaiiSam** [comment]
Hi @uniformization,

The Discord invite you are referring to is our Developer Discord which is yet to be publicly released. We will hopefully be allowing users to join in the next couple of weeks with that invite still being valid!
